var quotes = [
  "STEVE SMITH ALWAYS REPEAT \"STOP RAPING YOURSELF\" WHEN ASSAULTING HIKERS! STEVE NOT WORRIED ABOUT PROSECUTION, JUST FIND FUNNY!",
  "STEVE WANT RAPE NUTRASWEET, BUT TOO AFRAID OF WAY NUTRASWEET REACT! MAYBE LIKE TOO MUCH!",
  "STEVE SMITH NOT REMEMBER WRITE THIS",
  "STEVE SMITH'S PEOPLE NOT LET ON NOAH'S ARK. STEVE SMITH'S PEOPLE HAD TO RAPE WHALES FOR 40 SEXY WHALE DAYS AND 40 SEXY WHALE NIGHTS. ALL IS WRITTEN IN SACRED BOOK OF STEVE SMITH'S PEOPLE: THE INA GOD-DUH DURR VEDAS.",
  "STEVE SMITH SYMPATHISE WITH WOMEN PLIGHT! STEVE SMITH SUGGEST FEMINISTS COME FOR RAPING CONSCIOUSNESS MEETING IN CAVE!",
  "STEVE SMITH LIKE FRENCH WOMEN! STEVE SMITH AND FRENCH WOMEN SHARE GROOMING HABITS! STEVE SMITH MISSES REASON WHILE BACKPACKING! STEVE SMITH SEND POSTCARD! STEVE SMITH WISH YOU WERE HERE! SO STEVE SMITH COULD RAPE YOU!",
  "STEVE SMITH CALL BULLSHIT ON MAX! QUALITY OF STEVE SMITH RAPE AND STEVE SMITH FOOD ONLY GET BETTER OVER PAST DECADES! STEVE SMITH NOT GET SICK FROM ILL HIKERS IN LONG TIME! MAX KNOW THIS WHY STEVE SMITH NOT LIKE RAPE MAX! MAX NOT HEALTHY RAPE!",
  "STEVE SMITH NAIL CARTOONS! STEVE SMITH LIKE RAPE CARTOONS! STEVE SMITH RAPE BEFORE HAND!",
  "STEVE SMITH INCITED BY POLITICAL RHETORIC TO RAPE JANE JETSON! AND SCOOBY DOO!",
  "STEVE SMITH NO RAPE CONTRAIL. CHEMTRAIL GIVE CANCER OF THE RAPE. STEVE SMITH HEARD THIS WHEN RAPING ALEX JONES.",
  "STEVE SMITH COULD SAY SOMETHING ABOUT OBVIOUS ESL STATUS OF REASON PROOFREADERS, BUT STEVE SMITH TOO BUSY FORAGING FOR DELICIOUS ACORNS!",
  "\"Please don't rape the acorns Steve.\" STEVE SMITH MAKE NO PROMISES."
];

function randomSteveSmithQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)];
}